### ISSUE TITLE
准备搞这个了 https://gems.ruby-china.org

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/rubygems-mirror#1]
@qhwa 先考察一下服务器放在哪个地区在国内快

需要资金：

1. 约 $ 50/月 服务器费用； @jasl 
2. gems.ruby-china.org SSL 证书费用；@lgn21st 
3. 需要一个国内 CDN 赞助，以节约主服务器的网络开销 @lgn21st 

这次由 @qhwa 来主导

其实我已经初步考察了一下新的方案， http://gems.ruby-china.org 已经可以用了，但还有挺多细节需要完善。

**Comment by chloerei** [comment]
注意服务器安全，ssh key 登录，关闭密码登录，屏蔽不必要的端口。

Jason Lee <notifications@github.com>于2016年3月7日周一 上午10:36写道：

**Comment by jasl** [comment]
我计算一下，明中午前回复你

--
Jasl
Sent with Airmail


On March 7, 2016 at 10:36:46, Jason Lee (notifications@github.com<mailto:notifications@github.com>) wrote:

@qhwa<https://github.com/qhwa> 先考察一下服务器放在哪个地区在国内快

需要资金：

  1.  约 $ 50/月 服务器费用； @jasl<https://github.com/jasl>
  2.  gems.ruby-china.org SSL 证书费用；@lgn21st<https://github.com/lgn21st>
  3.  需要一个国内 CDN 赞助，以节约主服务器的网络开销 @lgn21st<https://github.com/lgn21st>

这次由 @qhwa<https://github.com/qhwa> 来主导

其实我已经初步考察了一下新的方案， http://gems.ruby-china.org 已经可以用了，但还有挺多细节需要完善。

**Comment by huacnlee** [comment]
国内用上了 UCloud 的 CDN，已经绑定上了，对 /gems/, /quick/ 两个目录的文件缓存 14 天

**Comment by qhwa** [comment]
证书不需要费用吧？我们试试直接用 LetEncrypt 吧！

**Comment by huacnlee** [comment]
可以的

我已经差不多部署上了，后面还需要完善很多细节部分

https://gitter.im/ruby-china/rubygems-mirror?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

 上 Gitter 聊

qhwa <notifications@github.com>于2016年3月7日周一 下午4:01写道：
