### ISSUE TITLE
502 错误

### ISSUE THREAD

**Issue by oneapmIO** [ruby-china/rubygems-mirror#10]
Gem::RemoteFetcher::FetchError: bad response Bad Gateway 502 (https://gems.ruby-china.org/gems/logster-1.1.1.gem)

**Comment by oneapmIO** [comment]
阿里云中拉gem出现的，互掐？

**Comment by oneapmIO** [comment]
Gem::RemoteFetcher::FetchError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://gems.ruby-china.org/gems/rack-mini-profiler-0.9.9.2.gem)

**Comment by oneapmIO** [comment]
I, [2016-03-17T09:05:23.106893 #37]  INFO -- : Error fetching https://gems.ruby-china.org/:
	SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://gems.ruby-china.org/specs.4.8.gz)

**Comment by huacnlee** [comment]
Duplicate #8
