### ISSUE TITLE
证书问题

### ISSUE THREAD

**Issue by shengliang1984** [ruby-china/rubygems-mirror#101]
root@ubuntu:~# gem sources -a https://gems.ruby-china.org
Error fetching https://gems.ruby-china.org:
        SSL_connect returned=1 errno=0 state=unknown state: sslv3 alert handshake failure (https://gems.ruby-china.org/specs.4.8.gz)
root@ubuntu:~# 

你好，上面是我在ubuntu14.04上的报错。请帮忙帮忙看下

**Comment by huacnlee** [comment]
相同问题

https://github.com/ruby-china/rubygems-mirror/issues/102
