### ISSUE TITLE
源无法删除或者更新

### ISSUE THREAD

**Issue by SunsgneDZ** [ruby-china/rubygems-mirror#104]
1.Sunsgne:~ sunsgne$ gem sources --remove https://ruby.taobao.org/ 
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /Users/sunsgne/.gemrc

2.Sunsgne:~ sunsgne$ gem sources -a https://gems.ruby-china.com/
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /Users/sunsgne/.gemrc

由于第一个过期了。

**Comment by KOElight** [comment]
我也遇到同样问题，哪位大神解答一下？

**Comment by huacnlee** [comment]
ERROR: While executing gem ... (Errno::EACCES)
Permission denied @ rb_sysopen - /Users/sunsgne/.gemrc


文件权限问题，删除那个文件先
