### ISSUE TITLE
詢問 mirror 源代碼

### ISSUE THREAD

**Issue by david50407** [ruby-china/rubygems-mirror#107]
想問是否有執行 mirror (caching) 及 bundler-api 部分的源代碼，想自己搞一個 mirror 但看了一下這個 repo 似乎只有前段的 code，沒有後半部分的邏輯代碼

**Comment by david50407** [comment]
ok 所以是沒有 感謝

**Comment by huacnlee** [comment]
CDN 做的，没有这些东西
