### ISSUE TITLE
Error fetching https://gems.ruby-china.org/

### ISSUE THREAD

**Issue by cocoddy** [ruby-china/rubygems-mirror#11]
Error fetching https://gems.ruby-china.org/:
        SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: ce
rtificate verify failed (https://gems.ruby-china.org/specs.4.8.gz)

**Comment by huacnlee** [comment]
https://github.com/ruby-china/rubygems-mirror/issues/3
