### ISSUE TITLE
腾讯云域名与证书不匹配？

### ISSUE THREAD

**Issue by huiping** [ruby-china/rubygems-mirror#13]
```
ERROR:  While executing gem ... (OpenSSL::SSL::SSLError)
    hostname "gems-10023966.file.myqcloud.com" does not match the server certificate
```

**Comment by huacnlee** [comment]
https://www.sslshopper.com/ssl-checker.html#hostname=gems-10023966.file.myqcloud.com

证书是确定有效的，请检查本地的问题

**Comment by huacnlee** [comment]
<img width="560" alt="2016-03-24 10 39 53" src="https://cloud.githubusercontent.com/assets/5518/14006907/ca3c9312-f1ac-11e5-83b7-3fba4c433492.png">

**Comment by huacnlee** [comment]
保持开着，其他人也会遇到

**Comment by xckevin** [comment]
我也遇到同样的问题，是偶发的。
貌似还比较普遍，社区里也有不少人遇见同样的问题[https://ruby-china.org/topics/29250](https://ruby-china.org/topics/29250)

**Comment by gongyang** [comment]
确实是有这样的问题
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    hostname "gems-10023966.file.myqcloud.com" does not match the server certificate (https://gems-10023966.file.myqcloud.com/quick/Marshal.4.8/rake-11.1.2.gemspec.rz)

我用wget会有下面报错
ERROR: certificate common name `*.cdn.myqcloud.com' doesn't match requested host name `gems-10023966.file.myqcloud.com'.
好像解析到 *.cdn.myqcloud.com这个域名上，导致不能match requested host name `gems-10023966.file.myqcloud.com'.

**Comment by gongyang** [comment]
@huiping  你的这个问题hostname "gems-10023966.file.myqcloud.com" does not match the server certificate解决了吗

**Comment by Shawkaine** [comment]
[https://github.com/google/google-api-ruby-client/issues/235](url)  照@fletchrichman 的办法
下载 http://curl.haxx.se/ca/cacert.pem, 并替换 /usr/local/etc/openssl/cert.pem. I've added export SSL_CERT_FILE=/usr/local/etc/openssl/cert.pem to my .bash_profile.   没用……

**Comment by bingosummer** [comment]
我也遇到了这个问题：
```
ERROR:  While executing gem ... (OpenSSL::SSL::SSLError)
    hostname "gems-10023966.file.myqcloud.com" does not match the server certificate
```

使用ruby.taobao.org好像没有这个问题。

**Comment by huacnlee** [comment]
这一定是你们的问题，我昨天才尝试新安装了一台 Ubuntu Server 14.04 的机器，所有环境都是重头安装的，没有遇到一次 SSL 证书的问题。

建议大家尝试用 https://github.com/huacnlee/init.d 这个脚本库来准备部署环境

**Comment by bingosummer** [comment]
谢谢 @huacnlee 

我会尝试使用你提供的脚本准备环境。

考虑到很多人都遇到了这个问题，有人找到是什么原因导致了这个问题吗？

**Comment by cmal** [comment]
我也遇到同样的问题，只能多运行几次，大多数时候会成功的

**Comment by Perish** [comment]
ERROR:  While executing gem ... (OpenSSL::SSL::SSLError)
    hostname "gems-10023966.file.myqcloud.com" does not match the server certificate

**Comment by huacnlee** [comment]
以上 SSL 有问题的，请尝试用 RVM 安装 Ruby，然后

```bash
$ rvm requirements
$ rvm reinstall 2.3.0
```

**Comment by Shawkaine** [comment]
用rbenv装的2.2.4……设置了全局用2.2.4……然鹅还是有这个问题

**Comment by bingosummer** [comment]
我用了@huacnlee 的脚本，确实没有证书的问题了。看来必须用RVM才行。

**Comment by huiping** [comment]
@gongyang 其实我没有解决，只是不知道为什么不再出现了😂😂😂，准备坐享大家研究成果

**Comment by huacnlee** [comment]
今天把前面的 CDN 换了了 UpYun，SSL 证书不同了
各位方便的话可以重新试试，给我个反馈

**Comment by bingosummer** [comment]
@huacnlee 
安装了几个gems，都没有遇到SSL证书的问题。
