### ISSUE TITLE
ERROR:  Could not find a valid gem '4.2.2' (>= 0) in any repository

### ISSUE THREAD

**Issue by dannysuen** [ruby-china/rubygems-mirror#14]
使用ruby-china镜像

$ gem install rails 4.2.2
Successfully installed rails-4.2.6
Parsing documentation for rails-4.2.6
Done installing documentation for rails after 0 seconds
ERROR:  Could not find a valid gem '4.2.2' (>= 0) in any repository

**Comment by huacnlee** [comment]
你的命令输入不对！

```bash
$ gem install rails -v '4.2.2'
```
