### ISSUE TITLE
添加 Ruby 源代码镜像的文档

### ISSUE THREAD

**Issue by wenweih** [ruby-china/rubygems-mirror#15]
### 修改 RVM ，改用本站作为下载源, 提高安装速度。
- FOR MAC  
  ```$ sed -i .bak -E 's!https?://cache.ruby-lang.org/pub/ruby!https://gems.ruby-china.org/mirrors/ruby!' $rvm_path/config/db```  
- FOR LINUX  
  ```$ sed -i -E 's!https?://cache.ruby-lang.org/pub/ruby!https://gems.ruby-china.org/mirrors/ruby!' $rvm_path/config/db```

**Comment by cybertk** [comment]
404 Not found when access https://gems.ruby-china.org/mirrors/ruby/

**Comment by huacnlee** [comment]
https://cache.ruby-china.org
