### ISSUE TITLE
gem install 错误

### ISSUE THREAD

**Issue by chaz1942** [ruby-china/rubygems-mirror#17]
$gem install orm_adapter
Fetching: orm_adapter-0.5.0.gem (  0B)
ERROR:  Error installing orm_adapter:
	invalid gem: package metadata is missing in /Users/chao/.rvm/gems/ruby-2.3.0/cache/orm_adapter-0.5.0.gem

在gem sources中添加ruby.taobao.org源后能正常安装

**Comment by huacnlee** [comment]
<img width="772" alt="2016-03-25 14 57 08" src="https://cloud.githubusercontent.com/assets/5518/14039691/e0e5b95c-f299-11e5-9cba-0ec2a8bedda6.png">

正常的呀

你删除这个文件试试

```bash
$ rm /Users/chao/.rvm/gems/ruby-2.3.0/cache/orm_adapter-0.5.0.gem
```

**Comment by chaz1942** [comment]
![f28959ce-4264-42f0-ad25-a8e09dd62c58](https://cloud.githubusercontent.com/assets/12437868/14040042/1ee9ad72-f29e-11e5-80d1-6512d19c2fc1.png)
我的是这个情况

**Comment by huacnlee** [comment]
执行后面加  -V （大写的）看看是什么情况

gem install orm_adapter -V

chaz1942 <notifications@github.com>于2016年3月25日周五 下午3:28写道：

**Comment by chaz1942** [comment]
嗯嗯 加－V好了   很感谢
