### ISSUE TITLE
Error fetching https://gems.ruby-china.org/

### ISSUE THREAD

**Issue by w304807481** [ruby-china/rubygems-mirror#21]
输入如下命令：
gem sources --add https://gems.ruby-china.org/ --remove https://rubygems.org/

出错：
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://gems.ruby-china.org/specs.4.8.gz)

**Comment by huacnlee** [comment]
https://github.com/ruby-china/rubygems-mirror/issues/3

**Comment by coooliang** [comment]
right now url is 
https://gems.ruby-china.com/
