### ISSUE TITLE
gem sources --add https://gems.ruby-china.org/  失败

### ISSUE THREAD

**Issue by xianer0405** [ruby-china/rubygems-mirror#23]
C:\Users\Jack>gem sources --add https://gems.ruby-china.org/                    
Error fetching https://gems.ruby-china.org/: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://gems.ruby-china.org/specs.4.8.gz)      

我的系统是Win10 64位

**Comment by hasbug** [comment]
一样挂了

**Comment by xianer0405** [comment]
![image](https://cloud.githubusercontent.com/assets/3275868/14404148/2cd32cc8-fea2-11e5-88d3-4e57f12c5f3d.png)

在慕课网的《Sass和Compass必备技能之Sass篇》中的评论中找到的。

**Comment by hasbug** [comment]
非常感谢，我昨晚最后网上找个免费一天的vpn出墙装的，哈哈。

**Comment by Alan-Liang** [comment]
[相关issue](https://github.com/alibaba/ruby.taobao.org/issues/54)

**Comment by bubbleatgit** [comment]
这种问题一般都是网络问题，可以多尝试几次，或者换个源，如mirrors.ustc.deu.cn/rubygems 这是中科大的镜像

**Comment by huacnlee** [comment]
如果遇到 SSL 证书问题，你又无法解决，请直接用 http://gems.ruby-china.org 避免 SSL 的问题。

**Comment by shjustinzhang** [comment]
Win10得环境，感觉行不通了呀，有高人指点？

C:\Users\juntizha>gem sources --add https://gems.ruby-china.com/
Error fetching https://gems.ruby-china.com/:
        SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://gems.ruby-china.com/specs.4.8.gz)

**Comment by huacnlee** [comment]
@shjustinzhang 用 WSL，你就算解决了这个问题，后面还会遇到其他各种各样问题的。

https://docs.microsoft.com/en-us/windows/wsl/install

**Comment by shjustinzhang** [comment]
> Win10得环境，感觉行不通了呀，有高人指点？
> 
> C:\Users\juntizha>gem sources --add https://gems.ruby-china.com/ Error fetching https://gems.ruby-china.com/: SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://gems.ruby-china.com/specs.4.8.gz)

解决办法

Download the cacert.pem file from http://curl.haxx.se/ca/cacert.pem. Save this file to your Ruby folder example

C:\Username\Ruby

Then run the command gem sources --add https://gems.ruby-china.com/
