### ISSUE TITLE
Bad Gateway 502

### ISSUE THREAD

**Issue by trevorwang** [ruby-china/rubygems-mirror#25]
前几天更新还没有问题 
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Bad Gateway 502 (https://gems-ruby-china.b0.upaiyun.com/gems/gym-1.6.3.gem)

--------
Updating installed gems
Updating bundler
Fetching: bundler-1.12.3.gem (100%)
Successfully installed bundler-1.12.3
Parsing documentation for bundler-1.12.3
Installing ri documentation for bundler-1.12.3
Installing darkfish documentation for bundler-1.12.3
Done installing documentation for bundler after 7 seconds
Parsing documentation for bundler-1.12.3
Done installing documentation for bundler after 3 seconds
Updating colorator
Fetching: colorator-1.0.0.gem (100%)
Successfully installed colorator-1.0.0
Parsing documentation for colorator-1.0.0
Installing ri documentation for colorator-1.0.0
Installing darkfish documentation for colorator-1.0.0
Done installing documentation for colorator after 0 seconds
Parsing documentation for colorator-1.0.0
Done installing documentation for colorator after 0 seconds
Updating concurrent-ruby
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Gateway Time-out 504 (https://gems-ruby-china.b0.upaiyun.com/quick/Marshal.4.8/concurrent-ruby-1.0.2.gemspec.rz)

------

/usr/local/lib/ruby/gems/2.2.0/gems/concurrent-ruby-1.0.2/lib/concurrent/tuple.rb
/usr/local/lib/ruby/gems/2.2.0/gems/concurrent-ruby-1.0.2/lib/concurrent/tvar.rb
/usr/local/lib/ruby/gems/2.2.0/gems/concurrent-ruby-1.0.2/lib/concurrent/utility/at_exit.rb
/usr/local/lib/ruby/gems/2.2.0/gems/concurrent-ruby-1.0.2/lib/concurrent/utility/engine.rb
/usr/local/lib/ruby/gems/2.2.0/gems/concurrent-ruby-1.0.2/lib/concurrent/utility/monotonic_time.rb
/usr/local/lib/ruby/gems/2.2.0/gems/concurrent-ruby-1.0.2/lib/concurrent/utility/native_extension_loader.rb
/usr/local/lib/ruby/gems/2.2.0/gems/concurrent-ruby-1.0.2/lib/concurrent/utility/processor_counter.rb
/usr/local/lib/ruby/gems/2.2.0/gems/concurrent-ruby-1.0.2/lib/concurrent/version.rb
Successfully installed concurrent-ruby-1.0.2
Parsing documentation for concurrent-ruby-1.0.2
Parsing sources...
100% [125/125]  lib/concurrent/version.rb
Installing ri documentation for concurrent-ruby-1.0.2
Installing darkfish documentation for concurrent-ruby-1.0.2
Done installing documentation for concurrent-ruby after 7 seconds
Parsing documentation for concurrent-ruby-1.0.2
Parsing sources...
100% [125/125]  lib/concurrent/version.rb
Done installing documentation for concurrent-ruby after 1 seconds
Updating curb
HEAD https://gems.ruby-china.org/api/v1/dependencies
200 OK
GET https://gems.ruby-china.org/api/v1/dependencies?gems=curb
200 OK
GET https://gems.ruby-china.org/quick/Marshal.4.8/curb-0.9.3.gemspec.rz
302 Moved Temporarily
GET https://gems-ruby-china.b0.upaiyun.com/quick/Marshal.4.8/curb-0.9.3.gemspec.rz
connection reset after 1 requests, retrying
GET https://gems-ruby-china.b0.upaiyun.com/quick/Marshal.4.8/curb-0.9.3.gemspec.rz
200 OK
Downloading gem curb-0.9.3.gem
GET https://gems.ruby-china.org/gems/curb-0.9.3.gem
302 Moved Temporarily
GET https://gems-ruby-china.b0.upaiyun.com/gems/curb-0.9.3.gem
502 Bad Gateway
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Bad Gateway 502 (https://gems-ruby-china.b0.upaiyun.com/gems/curb-0.9.3.gem)

**Comment by huacnlee** [comment]
UpYun 不够稳定，这个问题间歇性的发生，也是最近两天我也发现，之前一直都稳定了一个月了

**Comment by blackHandsome** [comment]
刚刚换了源也是这个Bad Gateway 502问题....一直搞不定我还说是不是我哪里出了问题...

**Comment by huacnlee** [comment]
相关说明: https://ruby-china.org/topics/29978
