### ISSUE TITLE
经典问题ssl

### ISSUE THREAD

**Issue by houbaron** [ruby-china/rubygems-mirror#26]
Error fetching https://gems.ruby-china.org/:
        SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://gems.ruby-china.org/specs.4.8.gz)

win10 x64

**Comment by huacnlee** [comment]
用 HTTP

**Comment by houbaron** [comment]
转了两三天，终于弄好了，感谢你们的镜像！祝愿大家早日摆脱WINDOWS，早日肉身翻墙。

**Comment by jasl** [comment]
等WSL出来就好啦~ 应该是7月底

**Comment by zhanggang807** [comment]
设置表示证书路径的环境变量 ： SSL_CERT_FILE  到你的ruby安装目录下有一个名为caert.pem的文件就ok了

**Comment by Eric-Guo** [comment]
WSL是指什么？@jasl

**Comment by jasl** [comment]
@Eric-Guo Windows Subsystem for Linux 简而言之，微软在内核里实现了全部的Linux系统调用 并且打包了一个Ubuntu在windows里，直接结果就是，可以以源生方式运行Linux应用
