### ISSUE TITLE
https://gems.ruby-china.com源503了

### ISSUE THREAD

**Issue by dhuSaverin** [ruby-china/rubygems-mirror#264]
<img width="952" alt="image" src="https://user-images.githubusercontent.com/21357856/78854564-38fa7100-7a54-11ea-9152-73957d1c10c2.png">

**Comment by xkkker** [comment]
请问你也是bundle  install 失败吗？ @dhuSaverin

**Comment by dhuSaverin** [comment]
> 请问你也是bundle install 失败吗？ @dhuSaverin

是啊，ruby-china源用不了了
