### ISSUE TITLE
bad response Gateway Time-out 504 

### ISSUE THREAD

**Issue by chen7897499** [ruby-china/rubygems-mirror#29]
``` bash
vagrant@precise64:~/data$ curl -I https://gems-ruby-china.b0.upaiyun.com/gems/notiffany-0.1.1.gem
HTTP/1.1 504 Gateway Time-out
Server: marco/0.16
Date: Sun, 31 Jul 2016 05:55:28 GMT
Content-Type: text/html
Content-Length: 181
Connection: keep-alive
Age: 10
X-Cache: MISS from mix-bj-pek-102, MISS from cun-tj-tsn-074
X-Request-Id: a35562bad49af890fdfab5a08ac2d6c8
Via: T.77103.M.1, V.mix-bj-pek-102, T.1412.M.1, M.cun-tj-tsn-074
```

``` bash
Gem::RemoteFetcher::FetchError: bad response Gateway Time-out 504 (https://gems-ruby-china.b0.upaiyun.com/gems/notiffany-0.1.1.gem)
Installing pry 0.10.4
Installing rspec-core 3.5.2
Installing rspec-expectations 3.5.0
Installing rspec-mocks 3.5.0
An error occurred while installing unicode-display_width (0.1.1), and Bundler cannot continue.
Make sure that `gem install unicode-display_width -v '0.1.1'` succeeds before bundling.
```

换到https://ruby.taobao.org 就没问题了

**Comment by huacnlee** [comment]
这个问题暂时无法解决，UpYun CDN 在发现新 Gem 的时候，本地没有 Cache，需要请求 rubygems.org 的源头下载 Gem 文件，这个过程可能会遇到超时的问题。

但这类情况，一般重试一下就可以了（此外由于新 Gem 的安装都是在开发环境命中的，发布的时候理论上是不会遇到的）

**Comment by Ehekatl** [comment]
发布环境无法换源 

```
Error fetching https://gems.ruby-china.org/:
        bad response Gateway Time-out 504 (https://gems-ruby-china.b0.upaiyun.com/specs.4.8.gz)
```
curl 却没问题

**Comment by holax** [comment]
无法更换源
`➜  /Users/Phoenix >gem sources --add https://gems.ruby-china.org/
Error fetching https://gems.ruby-china.org/:
	no such name (https://gems.ruby-china.org/specs.4.8.gz)`

**Comment by huacnlee** [comment]
ping gems.ruby-china.org 告诉我 IP @holax

**Comment by chenyawei** [comment]
alex@bogon  ~/Downloads/rubygems-2.6.8  ping gems.ruby-china.org
PING gems.ruby-china.org (115.159.216.235): 56 data bytes
64 bytes from 115.159.216.235: icmp_seq=0 ttl=50 time=34.559 ms
64 bytes from 115.159.216.235: icmp_seq=1 ttl=50 time=35.316 ms
64 bytes from 115.159.216.235: icmp_seq=2 ttl=50 time=34.672 ms
^C
--- gems.ruby-china.org ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 34.559/34.849/35.316/0.333 ms
 alex@bogon  ~/Downloads/rubygems-2.6.8  curl -I https://gems.ruby-china.org/specs.4.8.gz
HTTP/1.1 302 Moved Temporarily
Server: nginx/1.10.1
Date: Fri, 18 Nov 2016 08:06:04 GMT
Content-Type: text/html
Content-Length: 161
Connection: keep-alive
Location: https://gems-ruby-china.b0.upaiyun.com/specs.4.8.gz

 alex@bogon  ~/Downloads/rubygems-2.6.8  gem sources --add http://gems.ruby-china.org
Error fetching http://gems.ruby-china.org:
	bad response Gateway Time-out 504 (http://gems-ruby-china.b0.upaiyun.com/specs.4.8.gz)

**Comment by huacnlee** [comment]
重试，在 specs.4.8 CDN cache 失效的时候，这个问题是有可能出现的

chenyawei <notifications@github.com>于2016年11月18日周五 下午4:06写道：
