### ISSUE TITLE
Windows 下 SSL 证书问题

### ISSUE THREAD

**Issue by MickeyHub** [ruby-china/rubygems-mirror#3]
添加源的时候
```ruby
gem sources --add https://gems.ruby-china.org/
```
报错:
```text
Error fetching https://gems.ruby-china.org/:
	hostname "gems.ruby-china.org" does not match the server certificate (https://gems.ruby-china.org/specs.4.8.gz)
```

**Comment by huacnlee** [comment]
Chrome 浏览器，打开，点击地址栏 HTTP 前面部分，给我看看，类似这样：

<img width="345" alt="2016-03-10 13 59 33" src="https://cloud.githubusercontent.com/assets/5518/13660807/583ea776-e6c8-11e5-828a-00de5626f8fd.png">

**Comment by MickeyHub** [comment]
![image](https://cloud.githubusercontent.com/assets/5426838/13660850/a984d240-e6c8-11e5-85fb-c033ccd0e370.png)

**Comment by huacnlee** [comment]
```
rvm pkg install openssl
rvm reinstall --all
```

需要安装 OpenSSL

**Comment by MickeyHub** [comment]
现在好像没有问题了
![image](https://cloud.githubusercontent.com/assets/5426838/13660951/8fffa196-e6c9-11e5-9ed6-889e8dd1ac93.png)

**Comment by MickeyHub** [comment]
openssl之前是最新的，现在添加可以了,不过早上在添加https的源的时候确实报了上面的错误

**Comment by huacnlee** [comment]
那有可能是 SSL 正式更新没那么快出来，因为上去的，可能地区的 CDN 没同步到位

MickeySha <notifications@github.com>于2016年3月10日周四 下午2:09写道：

**Comment by MickeyHub** [comment]
多谢多谢

**Comment by lgn21st** [comment]
@huacnlee 这个 issue 又 Open 了？

**Comment by huacnlee** [comment]
开着，给别人参考，免得又提交新 Issue

Daniel Lv <notifications@github.com>于2016年3月14日周一 上午10:50写道：

**Comment by lgn21st** [comment]
@huacnlee 那还不如放到 Wiki 的 FAQ 里面，我刚刚加了一条。

**Comment by huacnlee** [comment]
就这个一直看着好了
他们提交首先会看到的

Daniel Lv <notifications@github.com>于2016年3月14日周一 上午10:52写道：

**Comment by huacnlee** [comment]
<img width="458" alt="2016-03-17 15 04 15" src="https://cloud.githubusercontent.com/assets/5518/13838784/aa694bf8-ec51-11e5-9aa8-07533741c5f2.png">
<img width="601" alt="2016-03-17 15 03 26" src="https://cloud.githubusercontent.com/assets/5518/13838785/aca07a5e-ec51-11e5-8717-f51fbd7dccef.png">

https://www.sslshopper.com/ssl-checker.html#hostname=https://gems.ruby-china.org/

**Comment by singlemonkey** [comment]
```
C:\Users\Administrator>gem sources --add https://gems.ruby-china.org/
Error fetching https://gems.ruby-china.org/:
        SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://gems.ruby-china.org/specs.4.8.gz)
```
这个证书验证失败的问题如何解决啊，windows10下没有装rvm如何安装openssl呢？

**Comment by huacnlee** [comment]
如果你是 Windows，花时间也解决不了 SSL 的问题，请用 http://gems.ruby-china.org

**Comment by sanlengjingvv** [comment]
碰到这个错误`SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://gems.ruby-china.org/specs.4.8.gz)`
用[这里](https://gist.github.com/fnichol/867550)的方法解决的

**Comment by sakyaer** [comment]
帮了大忙，之前淘宝的好像是挂掉了

**Comment by Gaohaoyang** [comment]
@sanlengjingvv 感谢，使用这个你给的链接已经解决。
