### ISSUE TITLE
Error fetching https://gems.ruby-china.org/

### ISSUE THREAD

**Issue by happybirds** [ruby-china/rubygems-mirror#31]
Error fetching https://gems.ruby-china.org/:
	SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/specs.4.8.gz)

system: os x yosemite 10.10.5

gem 2.6.4

**Comment by huacnlee** [comment]
重试，这个问题应该不存在了

**Comment by happybirds** [comment]
可是我的问题还是存在。。？
我现在 进行以下操作，直接报错

> gem sources  --add https://gems.ruby-china.org/

Error fetching https://gems.ruby-china.org/:
	SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/specs.4.8.gz)

**Comment by huacnlee** [comment]
再试一下

**Comment by happybirds** [comment]
这下好了 👌
