### ISSUE TITLE
在添加源的时候遇到too many resets

### ISSUE THREAD

**Issue by maoshunyu** [ruby-china/rubygems-mirror#33]
![default](https://cloud.githubusercontent.com/assets/10005716/17552101/5e02bff4-5f30-11e6-9369-b9a5441ab29b.PNG)

**Comment by puttin** [comment]
其实不止添加源会出现

**Comment by DynamicAnt** [comment]
同样的问题，一直不成功

**Comment by huacnlee** [comment]
@puttin 你什么时候会遇到，截图看看

**Comment by puttin** [comment]
@huacnlee 最近好像很少遇到了

**Comment by huacnlee** [comment]
问题已修复
