### ISSUE TITLE
替换gem sources -a https://gems.ruby-china.org/此镜像的时候报出下面的错,请问要怎么解决

### ISSUE THREAD

**Issue by AgnesT** [ruby-china/rubygems-mirror#35]
RaydeMac:~ Ray-iOS$ gem sources -a https://gems.ruby-china.org/

ERROR:  While executing gem ... (Gem::Exception)
    Unable to require openssl, install OpenSSL and rebuild ruby (preferred) or use non-HTTPS sources

**Comment by huacnlee** [comment]
安装 Ruby 的时候没有正确安装 OpenSSL，需要重新安装 Ruby

**Comment by AgnesT** [comment]
重新安装的时候  提示我说已经安装过了但是没有连接
RaydeMac:~ Ray-iOS$ brew install ruby
Warning: ruby-2.3.1 already installed, it's just not linked

**Comment by huacnlee** [comment]
https://ruby-china.org/topics/3324
