### ISSUE TITLE
cocoa pods 无法安装第三方库

### ISSUE THREAD

**Issue by BinQSS** [ruby-china/rubygems-mirror#37]
测试安装 一个第三方类  ********
xiaolideMac-mini:~ Bin$ cd /Users/Bin/Desktop/未命名文件夹/dsadsad 
xiaolideMac-mini:dsadsad Bin$ pod install
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem cocoapods (>= 0.a) (Gem::GemNotFoundException)
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems.rb:298:in `activate_bin_path'
	from /usr/local/bin/pod:22:in `<main>'

工程路径 及Pod文件配置 都没错  
Xcode 8  Mac版本 OS X EI Capitan 10.11.6

gem 版本 **********
xiaolideMac-mini:dsadsad Bin$ gem -v
2.6.6

ruby 版本*********
xiaolideMac-mini:dsadsad Bin$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

镜像 *********
xiaolideMac-mini:dsadsad Bin$ gem sources -l
*** CURRENT SOURCES ***
https://gems.ruby-china.org/

**Comment by huacnlee** [comment]
```
gem install cocoapods
```
