### ISSUE TITLE
无法获取fastlane最新版本，换回官方源可以

### ISSUE THREAD

**Issue by ylovern** [ruby-china/rubygems-mirror#38]
➜  /Users/Guinsoo  >sudo gem update fastlane
Updating installed gems
Nothing to update
➜  /Users/Guinsoo  >fastlane -v
fastlane 1.104.0
➜  /Users/Guinsoo  >gem souces -l
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command souces
➜  /Users/Guinsoo  >gem sources -l
*** CURRENT SOURCES ***

http://gems.ruby-china.org
➜  /Users/Guinsoo  >gem sources -r http://gems.ruby-china.org
http://gems.ruby-china.org removed from sources
➜  /Users/Guinsoo  >gem sources -a http://rubygems.org/
https://rubygems.org is recommended for security over http://rubygems.org/

Do you want to add this insecure source? [yn]  y
http://rubygems.org/ added to sources
➜  /Users/Guinsoo  >sudo gem update fastlane
Password:
Updating installed gems
Updating fastlane
Fetching: spaceship-0.34.3.gem (100%)
Successfully installed spaceship-0.34.3

**Comment by fantasticfears** [comment]
`onebox-1.5.50` 也碰到了同样的问题

**Comment by huacnlee** [comment]
好像是有个 Bug

**Comment by huacnlee** [comment]
彻底解决了，同步的时候会通过 UpYun 的一个 CDN 代理获取新版本的描述信息，但这个地方配置不对，用了默认的 7day 缓存，然后一直拉不到新的，所以等于是 7 天一次更新了。

刚才调整了一下配置，这次同步的问题就对了。

**Comment by pinguo-gaoshan** [comment]
@huacnlee 我手动添加同步之后, 过几个小时我的小伙伴就又搜索不到了, 需要重新手动添加一次.
cocoapods 1.1.0.rc.3 这个gem

**Comment by huacnlee** [comment]
@pinguo-gaoshan 你的小伙伴用得不对

原理上应该是不可能出现你描述的状况的，同步到 gems.ruby-china.org 里面以后以及都写到数据库了。

**Comment by pinguo-gaoshan** [comment]
@huacnlee 你试一试 cocoapods 1.1.0.rc.3 这个gem , rubychina源就找不到. 我用手动添加之后, 当时能找到, 过几个小时后又提示找不到了

**Comment by huacnlee** [comment]
我的错，代理的 CDN 关于 prerelease 的缓存没清理，导致没有拉到新数据，然后程序错误的误认为没有那些东西，就 yank 了。

已修复。

**Comment by wcnjeusr** [comment]
fastlane依然无法更新到最新版本：
`sudo gem update fastlane -n /usr/local/bin --verbose
Updating installed gems
Getting SRV record failed: DNS result has no information for _rubygems._tcp.gems.ruby-china.org
GET https://gems.ruby-china.org/specs.4.8.gz
302 Moved Temporarily
GET https://gems-ruby-china.b0.upaiyun.com/specs.4.8.gz
304 Not Modified
Nothing to update`
`fastlane -v 
fastlane 2.1.1

#######################################################################
# fastlane 2.5.0 is available. You are on 2.1.1.
# It is recommended to use the latest version.
# Please update using `sudo gem update fastlane`.
#######################################################################`

**Comment by huacnlee** [comment]
@wcnjeusr 

```
sudo gem install fastlane -v
```

```
Getting SRV record failed: DNS result has no information for _rubygems._tcp.gems.ruby-china.org
HEAD https://gems.ruby-china.org/api/v1/dependencies
200 OK
GET https://gems.ruby-china.org/api/v1/dependencies?gems=fastlane
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.gems.ruby-china.org
GET https://gems.ruby-china.org/quick/Marshal.4.8/fastlane-2.5.0.gemspec.rz
302 Moved Temporarily
GET https://gems-ruby-china.b0.upaiyun.com/quick/Marshal.4.8/fastlane-2.5.0.gemspec.rz
200 OK
```
