### ISSUE TITLE
http://gems.ruby-china.org/specs.4.8.gz not found

### ISSUE THREAD

**Issue by puttin** [ruby-china/rubygems-mirror#4]
bad response Not Found 404 (http://gems.ruby-china.org/specs.4.8.gz) (http://gems.ruby-china.org/specs.4.8.gz) (Gem::RemoteFetcher::FetchError)

**Comment by huacnlee** [comment]
已修复

**Comment by puttin** [comment]
![awesome](https://camo.githubusercontent.com/9747469e875881187f5bf58187eac8a7796a1f75/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3734393836342f3538363638312f39333061363335322d633935342d313165322d393064612d6266613865306631653738352e706e67)
