### ISSUE TITLE
添加源的时候没有反应

### ISSUE THREAD

**Issue by JiaDingYi** [ruby-china/rubygems-mirror#41]
$ gem sources -a https://gems.ruby-china.org
终端输入命令之后始终没有反应

**Comment by INeedNZT** [comment]
我也是一样的问题...

**Comment by JiaDingYi** [comment]
@INeedNZT  多等一会就好了  哈哈哈 😂

**Comment by zhutongLILY** [comment]
修改成  $ gem sources -a http://gems.ruby-china.org 就可以了，也就是 http不是https

**Comment by huacnlee** [comment]
测了一下，没有问题的
