### ISSUE TITLE
gem sources --add https://gems.ruby-china.org/ 报错

### ISSUE THREAD

**Issue by zhutongLILY** [ruby-china/rubygems-mirror#42]
执行 gem sources --add https://gems.ruby-china.org/ 会报如下错误：
Error fetching https://gems.ruby-china.org/:
        SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: ce
rtificate verify failed (https://gems.ruby-china.org/specs.4.8.gz) 
然而执行：gem sources --add http://gems.ruby-china.org/ 可以修改成功，但是gem sources --add https://gems.ruby-china.org/是你们官方给的示例程序，

**Comment by jasl** [comment]
证书问题，你得升级机器的openssl（编译安装的话要链接到新的openssl版本去），这个网站上有写的应该。
你用 `http://` 能成功是因为没走 `https` 不需要证书
