### ISSUE TITLE
fastlane 依然还是1.104，但是rubygems.org都已经是1.106了

### ISSUE THREAD

**Issue by happybobo** [ruby-china/rubygems-mirror#43]
<img width="211" alt="81a03eab-03ce-4d7c-b875-14a6933a8bd1" src="https://cloud.githubusercontent.com/assets/7436408/19677137/7776e7e6-9aca-11e6-9675-92bc56e55b5d.png">
但是https://rubygems.org/gems/fastlane 早就到1.106了，是不是同步出问题了？
![453fc864-7bf3-4d2d-a983-0da206b1be4f](https://cloud.githubusercontent.com/assets/7436408/19677213/ca0b5154-9aca-11e6-9c32-77a5eb5834fd.png)

**Comment by huacnlee** [comment]
直接 
```bash
gem install fastlane
```

`gem search` 这个和实际的不对，我们没处理这个的接口

**Comment by happybobo** [comment]
果真是这样，感谢
