### ISSUE TITLE
bundle报错

### ISSUE THREAD

**Issue by bestboylm** [ruby-china/rubygems-mirror#47]
[git@master gitlab]$ which bundle
/usr/local/ruby/bin/bundle
[git@master gitlab]$ bundle install --deployment --without development test postgres aws kerberos
Could not find command "install --deployment --without development test postgres aws kerberos".

**Comment by huacnlee** [comment]
这个和这个仓库没关系

gem install bundler

**Comment by huacnlee** [comment]
请上 Ruby China 发帖求助
