### ISSUE TITLE
Error in gem install compass! 

### ISSUE THREAD

**Issue by bleedkaga** [ruby-china/rubygems-mirror#49]
Use command : gem install compass, error tips: 
![image](https://cloud.githubusercontent.com/assets/16076679/20660272/ae9c643e-b583-11e6-8bed-c75216305202.png). Help

**Comment by huacnlee** [comment]
![image](https://cloud.githubusercontent.com/assets/5518/21492945/8faea074-cc43-11e6-97c6-976713d2792c.png)

请重试
