### ISSUE TITLE
certificate verify failed (https://gems.ruby-china.org/specs.4.8.gz)

### ISSUE THREAD

**Issue by LittleNoah** [ruby-china/rubygems-mirror#5]
gem sources --add https://gems.ruby-china.org/
-------------------------------------------------------------------
Error fetching https://gems.ruby-china.org/:
        SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://gems.ruby-china.org/specs.4.8.gz)

**Comment by LittleNoah** [comment]
"http://" works

**Comment by huacnlee** [comment]
告诉我所在地

**Comment by huacnlee** [comment]
https://github.com/ruby-china/rubygems-mirror/issues/3

看这个 Issue，浏览器打开是否有问题，你的问题

**Comment by LittleNoah** [comment]
浏览器显示没问题
北京市 联通

**Comment by huacnlee** [comment]
```
curl -I https://gems.ruby-china.org/specs.4.8.gz
```

试试

**Comment by LittleNoah** [comment]
**curl**: (60) SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by LittleNoah** [comment]
win10, ruby from railsInstaller

**Comment by huacnlee** [comment]
Windows 问题...

你用 `http://` 的 Bug

**Comment by LittleNoah** [comment]
GG...以后会修复不？

**Comment by huacnlee** [comment]
这可能是你本地环境却某些东西导致的，我无法帮你解决

**Comment by lgn21st** [comment]
@LittleNoah 你看看这篇文章能否帮到你 https://ruby-china.org/topics/24840

**Comment by LittleNoah** [comment]
thx, 暂时先用http了

**Comment by LittleNoah** [comment]
ok我找到解决方法了
@huacnlee 

> ruby没有包含SSL证书，所以Https的链接被服务器拒绝。
> 
> 解决方法很简单，首先在这里下载证书(http://curl.haxx.se/ca/cacert.pem), 然后再环境变量里设置SSL_CERT_FILE这个环境变量，并把value指向这个文件

来源 [http://blog.csdn.net/leorowe/article/details/41968349](url)
谷歌没找到的百度找到了..果然具体国情具体问题
对这个问题加个FAQ？

**Comment by hantsy** [comment]
@LittleNoah @huacnlee 

More simply, you do not need set SSL_CERT_FILE environment variable. 

1. Download the certificate file, [ttp://curl.haxx.se/ca/cacert.pem](ttp://curl.haxx.se/ca/cacert.pem)
2. Locate your rubygems .
        #gem which rubygems
       D:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems.rb
3. Navtigate to *D:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems* folder, there is a **ssl-cert** folder there. 
4. Created a new folder named **gems.ruby-china.org** under **ssl-cert**.
5. Copy the downloaded certificate file to the new **gems.ruby-china.org**, in my system it is *D:\Ruby23-x64\lib\ruby\site_ruby\2.3.0\rubygems\ssl_certs\gems.ruby-china.org*.

Hope this is helpful.

**Comment by ppmeng** [comment]
@hantsy win7 64bit Ruby 2.3.1 works

**Comment by ppmeng** [comment]
@hantsy but Ruby 2.2.5 can't

**Comment by oslivan** [comment]
My version: Ruby 2.4.2p198, and system is Ubuntu 16.04.3 LTS, just added rubychina certificate to the system, it solved.
```
sudo cp cacert.pem /usr/share/ca-certificates/
sudo dpkg-reconfigure ca-certificates
```
