### ISSUE TITLE
又拍云的地址有一个特别慢

### ISSUE THREAD

**Issue by WoolenWang** [ruby-china/rubygems-mirror#53]
wget -c http://gems.ruby-china.org/Marshal.4.8.Z -O xxxa
--2016-12-30 02:20:07--  http://gems.ruby-china.org/Marshal.4.8.Z
正在解析主机 gems.ruby-china.org (gems.ruby-china.org)... 115.159.216.235
正在连接 gems.ruby-china.org (gems.ruby-china.org)|115.159.216.235|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 302 Moved Temporarily
位置：http://gems-ruby-china.b0.upaiyun.com/Marshal.4.8.Z [跟随至新的 URL]
--2016-12-30 02:20:07--  http://gems-ruby-china.b0.upaiyun.com/Marshal.4.8.Z
正在解析主机 gems-ruby-china.b0.upaiyun.com (gems-ruby-china.b0.upaiyun.com)... 1**21.201.98.2, 183.61.64.66**
正在连接 gems-ruby-china.b0.upaiyun.com (gems-ruby-china.b0.upaiyun.com)|**121.201.98.2**|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 206 Partial Content
长度：4835870 (4.6M)，剩余 2114908 (2.0M) [binary/octet-stream]
正在保存至: “xxxa”

xxxa                                                                100%[+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++=======================================================================>]   4.61M  18.9KB/s    in 2m 9s

**121.201.98.2 这个地址特别慢,在解析到 183.61.64.66 的时候就比较快.**

wget -c http://gems.ruby-china.org/Marshal.4.8.Z -O xxxa
--2016-12-30 02:20:01--  http://gems.ruby-china.org/Marshal.4.8.Z
正在解析主机 gems.ruby-china.org (gems.ruby-china.org)... 115.159.216.235
正在连接 gems.ruby-china.org (gems.ruby-china.org)|115.159.216.235|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 302 Moved Temporarily
位置：http://gems-ruby-china.b0.upaiyun.com/Marshal.4.8.Z [跟随至新的 URL]
--2016-12-30 02:20:01--  http://gems-ruby-china.b0.upaiyun.com/Marshal.4.8.Z
正在解析主机 gems-ruby-china.b0.upaiyun.com (gems-ruby-china.b0.upaiyun.com)... 183.61.64.66, 121.201.98.2, 2405:fd80:110:0:d63d:7eff:fe73:c46
正在连接 gems-ruby-china.b0.upaiyun.com (gems-ruby-china.b0.upaiyun.com)|183.61.64.66|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 206 Partial Content
长度：4835870 (4.6M)，剩余 3004917 (2.9M) [binary/octet-stream]
正在保存至: “xxxa”

xxxa                                                                 55%[+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++============================>                                                                         ]   2.56M   192KB/s    eta 11s

**Comment by huacnlee** [comment]
那个文件缓存有效期短，实效的时候是从国外重新获取的，是正常情况
