### ISSUE TITLE
 gem sources --add with error EHOSTUNREACH

### ISSUE THREAD

**Issue by Xwoder** [ruby-china/rubygems-mirror#54]
$ gem sources --add http://gems.ruby-china.org/
Error fetching http://gems.ruby-china.org/:
	Errno::EHOSTUNREACH: Failed to open TCP connection to gems-ruby-china.b0.upaiyun.com:80 (No route to host - connect(2) for "gems-ruby-china.b0.upaiyun.com" port 80) (http://gems.ruby-china.org/specs.4.8.gz)

$ gem sources --add https://gems.ruby-china.org/
Error fetching https://gems.ruby-china.org/:
	Errno::EHOSTUNREACH: Failed to open TCP connection to gems-ruby-china.b0.upaiyun.com:443 (No route to host - connect(2) for "gems-ruby-china.b0.upaiyun.com" port 443) (https://gems.ruby-china.org/specs.4.8.gz)

不论是http还是https均报错

**Comment by huacnlee** [comment]
```
curl -V https://gems.ruby-china.org/specs.4.8.gz
```

看看

**Comment by Xwoder** [comment]
刚刚试了下gem sources --add，好了，可能是服务器不够稳定吧。
