### ISSUE TITLE
sources add失败

### ISSUE THREAD

**Issue by lilian132** [ruby-china/rubygems-mirror#56]
![image](https://cloud.githubusercontent.com/assets/4987042/22767523/b29de154-eeb6-11e6-9387-bce0b0d9346d.png)

PS D:\git\jsduck> gem sources --add https://gems.ruby-china.org/
Error fetching https://gems.ruby-china.org/:
        SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://gems.ruby-china.org/specs.4.8.gz)

**Comment by huacnlee** [comment]
Windows 用 http
