### ISSUE TITLE
gem install issue

### ISSUE THREAD

**Issue by chaoMaster** [ruby-china/rubygems-mirror#57]
我们经常会遇到类似这样的源的问题
[Tue Feb 14 14:44:15 UTC 2017]        Gem::RemoteFetcher::UnknownHostError: no such name (https://gems.ruby-china.org/gems/minitest-5.5.1.gem)
[Tue Feb 14 14:44:15 UTC 2017]        Gem::RemoteFetcher::UnknownHostError: no such name (https://gems.ruby-china.org/gems/json-1.8.2.gem)
[Tue Feb 14 14:44:15 UTC 2017]  !     Failed to install gems via Bundler.
[Tue Feb 14 14:44:15 UTC 2017]        An error occurred while installing json (1.8.2), and Bundler cannot continue.

在昨晚（2.14号）北京时间 22点左右，我们环境较为频繁的报出了以上这种问题。
这是当时有什么更新吗，如果没有能否告诉我们发生这种错误的原因呢。

由于我们自己有很多套环境，每套环境都有检测机制，需要较为频繁的向源请求数据，所以我们属于正常使用，而不是恶意攻击或者滥用之类。

**Comment by huacnlee** [comment]
服务器没有限制机制

**Comment by huacnlee** [comment]
看错误像是域名解析异常

告诉我哪个机器的 IP

**Comment by chaoMaster** [comment]
124.251.96.5
124.251.96.6
124.251.96.8
124.251.96.10
124.251.96.11
上面是我们几个环境的 ip
隔壁 issue 58 是我的同事，看到了你们的交流

**Comment by huacnlee** [comment]
我给了搞了，还有问题没？

**Comment by chaoMaster** [comment]
谢谢，再有问题我们再联系

**Comment by chaoMaster** [comment]
你好，今天下午（3.7）大概 15:05 左右时间段我们的环境在使用时发生了 403 错误，不知道当时是什么原因呢，是因为网络问题？还是？   

错误日志长下面这样
Gem::RemoteFetcher::FetchError: bad response Forbidden 403 (https://gems-ruby-china.b0.upaiyun.com/gems/minitest-5.5.1.gem) (STDOUT, STG)
