### ISSUE TITLE
运用rubyGems 安装 fastlane ,为何无法更新到最新的版本

### ISSUE THREAD

**Issue by JXwilliamJi** [ruby-china/rubygems-mirror#61]
查知: fastlane 最新的版本为2.18.2 ,本地版本为2.17.2 ,欲更新到最新的版本,使用命令 sudo gem update fastlane 更新 显示无新的内容

删除本地镜像,换为原来的rubgGems地址,更新成功!

为什么?不是保持实时更新的么?

**Comment by huacnlee** [comment]
<img width="1074" alt="2017-02-23 2 06 47" src="https://cloud.githubusercontent.com/assets/5518/23246840/57401180-f9d1-11e6-9484-2112aab8ddb0.png">

这是刚刚执行的，有 2.18.2
