### ISSUE TITLE
添加gem源的地址错误

### ISSUE THREAD

**Issue by Shenchuanhuan** [ruby-china/rubygems-mirror#62]
官网上的：https://gems.ruby-china.org
![官网操作提示](https://cloud.githubusercontent.com/assets/24203427/23340552/4c26059e-fc73-11e6-8729-dc9eb839a480.png)

[https://gems.ruby-china.org/](https://gems.ruby-china.org/)添加gem源后报错：
![gem](https://cloud.githubusercontent.com/assets/24203427/23340550/44d70bc6-fc73-11e6-91f8-30b06084c4f2.png)

使用http://gems.ruby-china.org添加成功。

**Comment by jasl** [comment]
Win 10 的话用 WSL 然后通过 rvm 或者 rbenv 来安装 Ruby 吧，Cygwin 的 OpenSSL 有问题所以你只能用 HTTP 方式连接

**Comment by huacnlee** [comment]
如果遇到 SSL 证书问题，你又无法解决，请直接用 http://gems.ruby-china.org 避免 SSL 的问题。

我们无法帮助解决 Windows 环境运行的问题，没有相关的经验和精力。

所以，两种选择：

- 用 http 协议的方式；
- 不要用 Windows 环境，例如用 VirtualBox, Docker 之类的虚拟机，里面使用 Linux；
