### ISSUE TITLE
gem sources --add http://gems.ruby-china.org/ 报错

### ISSUE THREAD

**Issue by PolanZ** [ruby-china/rubygems-mirror#63]
gem sources --add http://gems.ruby-china.org/ --remove https://rubygems.org/

Error fetching http://gems.ruby-china.org/:
	no such name (http://gems.ruby-china.org/specs.4.8.gz)

用HTTPS也是一样的错误
gem sources --add https://gems.ruby-china.org/ --remove https://rubygems.org/
Error fetching https://gems.ruby-china.org/:
	no such name (https://gems.ruby-china.org/specs.4.8.gz)

**Comment by hmf19921224** [comment]
我也有这样的错误。不过再次更新一下就好了

**Comment by dby** [comment]
@hmf19921224  更新成功了吗

**Comment by studylearner** [comment]
localhost:~ cgs$ gem sources --add https://gems.ruby-china.org/ --remove https://rubygems.org/ --remove https://ruby.taobao.org
https://gems.ruby-china.org/ is not a URI
报这个错误

**Comment by studylearner** [comment]
localhost:~ cgs$ gem sources --add https://gems.ruby-china.org/ --remove https://rubygems.org/ --remove https://ruby.taobao.org
https://gems.ruby-china.org/ is not a URI  报这个错误

**Comment by haskio** [comment]
有同样的问题，
试过好几天，一直这样。不知道咋搞。

**Comment by SeongBrave** [comment]
@PolanZ  兄弟，遇到同样的问题，你那边解决了吗？如何解决的呢?
