### ISSUE TITLE
curl https://gems.ruby-china.org return 302

### ISSUE THREAD

**Issue by cathyfjl** [ruby-china/rubygems-mirror#64]
Hi,
   您好，我有个问题想咨询一下，在今天即2017/3/2这天的 11:31、19:36、20:40这三个时间点，在访问该源时网络返回值为302，几分钟后变为200，可否问一下，这三个时间点您那边有没有对该ruby源做什么样的操作？或者可否告知一下出现这样的返回值，是什么原因呢？烦请回复一下，非常感谢。

**Comment by cathyfjl** [comment]
https://gems.ruby-china.org/gems/i18n-0.7.0.gem
烦请问一下，curl这个地址一直报302，能否告知一下是什么原因呢？望您回复一下，谢谢

**Comment by huacnlee** [comment]
Duplication issue with #58
