### ISSUE TITLE
can not add sources

### ISSUE THREAD

**Issue by grubed** [ruby-china/rubygems-mirror#67]
![9 x84 lb shbwztxq 1 a x](https://cloud.githubusercontent.com/assets/21269645/23977246/fbea8a74-0a27-11e7-830f-3d635c0179a4.png)

**Comment by huacnlee** [comment]
重复问题

https://github.com/ruby-china/rubygems-mirror/issues/56

**Comment by grubed** [comment]
![m u 2x w05f_h 4m 9wxr6](https://cloud.githubusercontent.com/assets/21269645/23978753/a969f1f0-0a30-11e7-9c9f-0b0cd570dc5e.png)
哪里重复了？

**Comment by grubed** [comment]
@huacnlee 你有病吧，问题不解决就关闭

**Comment by huacnlee** [comment]
@grubed 说的好像我有义务给你解决问题似的？

**Comment by grubed** [comment]
@huacnlee 你不解决我需要别人帮我解决，你关闭了别人怎么帮我？

**Comment by grubed** [comment]
@huacnlee 你不想帮忙可以不忙，请不要阻碍我向别人求助

**Comment by huacnlee** [comment]
来求助，一点起码的礼貌都没有

**Comment by grubed** [comment]
@huacnlee 如果哪里有得罪的地方，请多包涵，向您道歉
