### ISSUE TITLE
gem添加源失败

### ISSUE THREAD

**Issue by grubed** [ruby-china/rubygems-mirror#68]
![image](https://cloud.githubusercontent.com/assets/21269645/23978873/42098fce-0a31-11e7-8f77-db82593d27cd.png)
![image](https://cloud.githubusercontent.com/assets/21269645/23978877/47d4ca22-0a31-11e7-81ae-df93e05ce317.png)

**Comment by huacnlee** [comment]
https://github.com/ruby-china/rubygems-mirror/issues/67
