### ISSUE TITLE
gem 失败

### ISSUE THREAD

**Issue by soiND** [ruby-china/rubygems-mirror#69]
xuyu~MacBook-Pro:~ xuyu$ gem sources -a https://gems.ruby-china.org/
Error fetching https://gems.ruby-china.org/:
	Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://gems.ruby-china.org/specs.4.8.gz)
-------------------------------------------------
macOS Sierra  版本10.12.1   
求解

**Comment by huacnlee** [comment]
```bash
curl -v https://gems.ruby-china.org/specs.4.8.gz
```

试试看呢

**Comment by huacnlee** [comment]
<img width="836" alt="2017-03-16 1 29 42" src="https://cloud.githubusercontent.com/assets/5518/23983059/a22a3faa-0a4c-11e7-9964-3604fec869d2.png">

**Comment by soiND** [comment]
xuyu~MacBook-Pro:~ xuyu$ curl -v https://gems.ruby-china.org/specs.4.8.gz
*   Trying 115.159.216.235...
* Connected to gems.ruby-china.org (115.159.216.235) port 443 (#0)
* Server aborted the SSL handshake
* Closing connection 0
curl: (35) Server aborted the SSL handshake
xuyu~MacBook-Pro:~ xuyu$ gem sources -l
*** CURRENT SOURCES ***

xuyu~MacBook-Pro:~ xuyu$

**Comment by huacnlee** [comment]
浏览器直接打开这个地址是否可以？

**Comment by soiND** [comment]
我现在是在公司的网,刚刚发现以下两个网址都打不开:
https://gems.ruby-china.org/specs.4.8.gz
https://gems.ruby-china.org/
我晚上回家再试试....
谢谢
