### ISSUE TITLE
跟换源后，bundle 出错

### ISSUE THREAD

**Issue by songjiayang** [ruby-china/rubygems-mirror#7]
运行 Ruby-China 源代码，执行 bundle , 提示错误信息如下：
~/open-source/ruby-china(master)$ bundle 
Fetching gem metadata from https://gems.ruby-china.org/.Retrying dependency api due to error (2/4): Bundler::HTTPError Network error while fetching https://gems.ruby-china.org/api/v1/dependencies?gems=rake%2Cconcurrent-ruby%2Ci18n%2Cminitest%2Cthread_safe%2Ctzinfo%2Cactivesupport%2Cbuilder%2Cerubis%2Cmini_portile2%2Cnokogiri%2Crails-deprecated_sanitizer%2Crails-dom-testing%2Cloofah%2Crails-html-sanitizer%2Cactionview%2Cjson%2Crack%2Crack-test%2Cactionpack%2Cnio4r%2Cwebsocket-extensions%2Cwebsocket-driver%2Cactioncable%2Cglobalid%2Cactivejob%2Cmime-types%2Cmail%2Cactionmailer%2Cactivemodel%2Cactive_model_serializers%2Carel%2Cactiverecord%2Caddressable%2Cast%2Cauto-space%2Cdescendants_tracker%2Cice_nine%2Caxiom-types%2Cbcrypt%2Cbenchmark-ips%2Ccoderay%2Cbetter_errors%2Cdebug_inspector%2Cbinding_of_caller%2Cthor%2Cbundler-audit%2Ccancancan%2Chighline%2Cnet-ssh
Retrying dependency api due to error (3/4): Bundler::HTTPError Network error while fetching https://gems.ruby-china.org/api/v1/dependencies?gems=net-scp%2Cnet-sftp%2Cnet-ssh-gateway%2Ccapistrano%2Cconnection_pool%2Credis%2Csidekiq%2Ccapistrano-sidekiq%2Cxpath%2Ccapybara%2Ccarrierwave%2Cmultipart-post%2Cfaraday%2Ccarrierwave-upyun%2Ccoercible%2Ccoffee-script-source%2Cexecjs%2Ccoffee-script%2Cmethod_source%2Crailties%2Ccoffee-rails%2Ccolorize%2Cdalli%2Cdatabase_cleaner%2Cget_process_mem%2Cheapy%2Cmemory_profiler%2Cderailed_benchmarks%2Cderailed%2Corm_adapter%2Cresponders%2Cwarden%2Cdevise%2Cdevise-encryptable%2Cdiff-lcs%2Cunf_ext%2Cunf%2Cdomain_name%2Cdoorkeeper%2Cdoorkeeper-i18n%2Csprockets%2Csprockets-rails%2Crails%2Cdropzonejs-rails%2Cmulti_json%2Celasticsearch-api%2Celasticsearch-transport%2Celasticsearch%2Chashie%2Celasticsearch-model
Retrying dependency api due to error (4/4): Bundler::HTTPError Net::HTTPBadGateway: 
```
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nnws/1.7.3.6</center>
</body>
</html>
```

**Comment by songjiayang** [comment]
重试几次过后就好了，可能 cdn 一开始没有镜像资源吧。

**Comment by huacnlee** [comment]
昨天我调整了一下，看时间应该是那个时候
