### ISSUE TITLE
报403

### ISSUE THREAD

**Issue by johntaiii** [ruby-china/rubygems-mirror#70]
sudo gem install -n /usr/local/bin cocoapods --pre

ERROR:  Could not find a valid gem 'cocoapods' (>= 0), here is why:
          Unable to download data from https://gems.ruby-china.org/ - bad response Forbidden 403 (https://gems-ruby-china.b0.upaiyun.com/specs.4.8.gz)

请问啥原因？

**Comment by huacnlee** [comment]
上次发现过一个问题，如果是国外服务器，某些地方可能无法访问。

貌似 UpYun 有些限制，上次我发现的是 Aliyun 香港的服务器。

你需要确定你翻墙的配置这个是走国内，还是国外的。

**Comment by johntaiii** [comment]
明白了，是美国的ip。谢谢。

**Comment by huacnlee** [comment]
我关闭了海外加速的功能（最近 UpYun 新出的，估计是这个问题），现在你再用之前的方式尝试一下呢？

**Comment by johntaiii** [comment]
还是报403

**Comment by TonyJR** [comment]
同样遇到这个问题，求解决

**Comment by huacnlee** [comment]
@johntaiii @TonyJR 不要翻墙访问

**Comment by TonyJR** [comment]
@huacnlee 之前是没翻墙，后来翻墙更新了一下gem版本解决了

**Comment by huacnlee** [comment]
@TonyJR 你是更新了一下 RubyGems ?

**Comment by TonyJR** [comment]
翻墙出去，然后gem update --system

**Comment by huacnlee** [comment]
我今天才发现，是我错误的配置了一个频率限制 🙈

抱歉了，各位，今天才检查出来，已经去掉了限制，这个问题应该彻底解决了。

**Comment by wanglizheng** [comment]
现在又出现这个问题了,求助

**Comment by jasl** [comment]
@wanglizheng 因为备案问题被暂时屏蔽，已经在处理了

**Comment by huacnlee** [comment]
用 https 请求，暂时
