### ISSUE TITLE
https://gems.ruby-china.org/ is not a URI

### ISSUE THREAD

**Issue by studylearner** [ruby-china/rubygems-mirror#74]
localhost:~ cgs$ gem sources --add https://gems.ruby-china.org/ --remove https://rubygems.org/ --remove https://ruby.taobao.org
https://gems.ruby-china.org/ is not a URI
咋解决啊

**Comment by huacnlee** [comment]
gem update --system

然后再试

**Comment by studylearner** [comment]
好的

**Comment by studylearner** [comment]
localhost:~ cgs$ gem update --system
ERROR:  While executing gem ... (URI::InvalidURIError)
    bad URI(is not URI?): <strong>https://ruby.taobao.org/<strong>

**Comment by studylearner** [comment]
全部重新删了 从来还是不行 就是报这个错误 @huacnlee

**Comment by huacnlee** [comment]
```
$ rm ~/.gemrc 
```

然后重试

**Comment by studylearner** [comment]
可以了 谢谢 @huacnlee
