### ISSUE TITLE
使用 HTTP 仍然有证书问题。

### ISSUE THREAD

**Issue by ply1xyz** [ruby-china/rubygems-mirror#78]
[root@localhost ~]# gem source -l
*** CURRENT SOURCES ***

http://gems.ruby-china.org/
[root@localhost ~]# gem update
Updating installed gems
Updating io-console
ERROR:  While executing gem ... (OpenSSL::SSL::SSLError)
    hostname "upyun.gems.ruby-china.org" does not match the server certificate

**Comment by vangie** [comment]
我也碰到了同样的问题

**Comment by lovingyu** [comment]
http 的也有ssl问题
`C:\Users\81440>gem sources -l
*** CURRENT SOURCES ***

http://gems.ruby-china.org/

C:\Users\81440>gem install webdrivers
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://upyun.gems.ruby-china.org/quick/Marshal.4.8/webdrivers-2.4.0.gemspec.rz)`

**Comment by jasl** [comment]
更新一下 openssl，你的操作系统版本是什么，怎么安装的

**Comment by lovingyu** [comment]
win10
cmd命令行执行的
以前都是可以的，就最近发现不行。

**Comment by vangie** [comment]
我的是 ubuntu 14.04，代码是写 dockerfile 里的，之前调试好了可以执行的，最执行的时候报错了。

```
# Ruby
RUN curl -sSL https://rvm.io/mpapis.asc | gpg --import - \
	&& curl -L https://get.rvm.io | bash -s stable \
	&& printf '\nsource ~/.rvm/scripts/rvm' >> ~/.bashrc
RUN bash -l -c "rvm requirements"
RUN bash -l -c "sed -i 's!cache.ruby-lang.org/pub/ruby!ruby.taobao.org/mirrors/ruby!' ~/.rvm/config/db"
RUN bash -l -c "rvm install 2.2.2"
RUN bash -l -c "gem sources --add http://gems.ruby-china.org/ --remove https://rubygems.org/ && gem sources -l && gem install bundler rails sqlite3"
RUN bash -l -c "bundle config mirror.https://rubygems.org http://gems.ruby-china.org"
```

**Comment by jasl** [comment]
我仍然怀疑是 SSL 版本导致的 @vangie 你可以尝试下更新到16.04 或者在这些命令之前 apt-get update && apt-get upgrade 一下么

**Comment by vangie** [comment]
@jasl 我这个 dockerfile 不方便升级新的 ubuntu，能否兼容一下低版本的 ssl。

**Comment by jasl** [comment]
@vangie 看这个 <http://guides.rubygems.org/ssl-certificate-update/>

**Comment by huacnlee** [comment]
```
RUN bash -l -c "sed -i 's!cache.ruby-lang.org/pub/ruby!ruby.taobao.org/mirrors/ruby!' ~/.rvm/config/db"
```

去掉这行

**Comment by huacnlee** [comment]
rvm install 之前，先确保 `apt-get install openssl`

**Comment by tq0fqeu** [comment]
+1 

> gem source -a http://gems.ruby-china.org
Error fetching http://gems.ruby-china.org:
	hostname "upyun.gems.ruby-china.org" does not match the server certificate (https://upyun.gems.ruby-china.org/specs.4.8.gz)

**Comment by huacnlee** [comment]
今天我调整了一下 CDN 配置，HTTP 不再回源到 HTTPS 协议，之前这么做是因为这样可以跳过服务器的备案限制，但这么做导致 Redirect To: upyun.gems.ruby-china.org 的动作都是 HTTPS 协议了。

根本问题还是大家要尝试自行解决 RubyGems 安装的 SSL 证书问题（Ruby China 有很多的资料，自行学习解决）。

----

目前调整的方式可能回导致 HTTP 的依然无法使用，因为服务器备案验证是基于 HTTP 协议（80 端口）的，我只是目前简单的测试了一下是可以用的。

**Comment by huacnlee** [comment]
试试配置 `~/.gemrc`

```yml
---
:sources:
- https://gems.ruby-china.org
:ssl_verify_mode: 0
```

**Comment by wangpengabc** [comment]
在ubuntu中安装两个ruby版本时，可能会出这种错误。我先安装的时2.6.5，gem是3.0.x; 然后安装的2.2.4，gem是2.3.x,然后在gem官网使用wget手动下载gem包，然后本地ruby setup.rb安装的gem 3.0.x,最后修改为http，发现添加镜像成功，可以正常安装bundler了
