### ISSUE TITLE
gem sources -a https://gems.ruby-china.org/  出错误，救命啊

### ISSUE THREAD

**Issue by qi20088** [ruby-china/rubygems-mirror#79]
错误如下：
Error fetching http://gems.ruby-china.org/:
	hostname was not match with the server certificate (https://upyun.gems.ruby-china.org/specs.4.8.gz)

**Comment by qi20088** [comment]
试过把https换成http也不行。一样的错误，我也是醉了。很多人遇到我一样的问题，怎么就没人回答呢处理呢，心累。。

**Comment by jasl** [comment]
`gem source -a https://upyun.gems.ruby-china.org`这样试试，最近开会严打，gem源遭遇备案问题，会间歇性挂掉

**Comment by qi20088** [comment]
老样子，一样的错误。 @jasl

**Comment by jasl** [comment]
那你更新下本机的openssl吧，记得让ruby链接到最新版的去，可能是版本太低了

**Comment by qi20088** [comment]
还能不能愉快地玩啊

**Comment by qi20088** [comment]
我本地的ruby 版本 

[root@boss_test1 logstash]# ruby -v 
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
@jasl

**Comment by jasl** [comment]
1.8.7 是不受支持的...快十年前的版本了... 升级到 2.0 以上

**Comment by qi20088** [comment]
和我的openssl有关系？ 请教下怎么更新 openssl 、ruby 。他们对应的指令分别是？
@jasl

**Comment by qi20088** [comment]
没玩过ruby，请原谅我对ruby版本的理解!
@jasl

**Comment by qi20088** [comment]
谢谢您给我耐心的讲解。 @jasl

**Comment by jasl** [comment]
用 rvm 安装就行了，他自己解决各种依赖的安装，具体自己查文档就好了，你如果不是特殊需要，就装最新版本（2.4.1），否则至少也要尽量用 2.2 以上的版本（Rails 5 也抛弃了 2.2 以下的支持）

**Comment by qi20088** [comment]
我是centos 6.9。 用rvm安装有相关的网址吗。
我找到了一个。https://github.com/huacnlee/init.d    不过是用于ubuntu的。不适合我
@jasl

**Comment by qi20088** [comment]
都没解决我的问题呢，怎么就关闭了呢。汗
@jasl

**Comment by jasl** [comment]
https://rvm.io/ 你搜一下啊。。。

**Comment by qi20088** [comment]
谢谢，我用rvm更新了。成功添加。太感谢你了！ @jasl
