### ISSUE TITLE
Bad Gateway 502 网关错误，已排除证书问题

### ISSUE THREAD

**Issue by fantasticfears** [ruby-china/rubygems-mirror#8]
这是生产环境部署 Discourse 的时候出现的 502 网关错误，[详细流水](https://ruby-china.org/topics/29250#reply88)。

尝试机器：阿里云上海的 139.196.41.197（ipip.net，应该是 BGP 机房了）
`uname -a`: `Linux iZ111shkmi6Z 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

可能原因及排除：
1. 回源超时；多次尝试过了，有的错误是 `gem update bundler` 时出现的，不应该是缓存超时了 #5 且确认不是 http 能解决的问题，curl -I https://gems.ruby-china.org/specs.4.8.gz 正常；
2. CA 证书问题：已经从 https://curl.haxx.se/ca/cacert.pem 下载文件并设置了 `SSL_CERT_FILE`（ #3  ），cat 确认过 CA 文件完整；
3. 部署问题：是 502 问题的一个原因；
4. CA 文件的权限：权限是属 root，不过执行操作的时候是 root 用户在执行，所以仍旧认为不是这个问题。
5. http 的情况：可以顺利 bundle，但是速度极慢，Discourse 部署相关的 gem 部署大概需要 18 分钟（镜像没理由这么慢啊...）。

相关 gist（Discourse 的配置模板）：https://gist.github.com/fantasticfears/822793950e6c0ca38b4b

**Comment by huacnlee** [comment]
Linux 上面不需要导 CA 证书的呀

**Comment by huacnlee** [comment]
502 本来说今天看 Nginx 日志的，结果有个目录不在日志没写入...

再等等观察看看

**Comment by fantasticfears** [comment]
刚起，加 CA 是确认下到底证书有没问题...

前面有个人和我说正常了但是有点慢，我还没继续跟下去

**Comment by huacnlee** [comment]
```bash
2016/03/16 15:38:29 [info] 1356#0: *108749 client 111.13.3.68 closed keepalive connection
2016/03/16 15:38:30 [info] 1356#0: *108751 client 117.172.5.150 closed keepalive connection
2016/03/16 15:38:30 [info] 1356#0: *108755 client 180.153.105.151 closed keepalive connection
2016/03/16 15:38:30 [info] 1356#0: *108753 client 119.147.33.19 closed keepalive connection
2016/03/16 15:38:30 [info] 1356#0: *108759 client 220.195.19.20 closed keepalive connection
2016/03/16 15:38:32 [info] 1356#0: *108765 client 180.153.105.152 closed keepalive connection (104: Connection reset by peer)
2016/03/16 15:38:32 [info] 1356#0: *108763 client 220.195.19.21 closed keepalive connection
2016/03/16 15:38:32 [info] 1356#0: *108757 client 42.56.65.20 closed keepalive connection
2016/03/16 15:38:32 [info] 1356#0: *108769 client 111.47.248.152 closed keepalive connection
2016/03/16 15:38:33 [info] 1356#0: *108767 client 122.72.53.11 closed keepalive connection
2016/03/16 15:38:34 [info] 1356#0: *108772 client 183.203.17.80 closed keepalive connection (104: Connection reset by peer)
2016/03/16 15:38:38 [info] 1356#0: *108410 client 115.231.191.145 closed keepalive connection (104: Connection reset by peer)
2016/03/16 15:38:40 [info] 1356#0: *108781 client 163.177.158.77 closed keepalive connection
2016/03/16 15:38:42 [info] 1356#0: *108789 client 113.200.90.150 closed keepalive connection
2016/03/16 15:38:48 [info] 1356#0: *108385 client 27.221.81.19 closed keepalive connection (104: Connection reset by peer)
2016/03/16 15:38:52 [info] 1356#0: *108393 client 119.147.253.14 closed keepalive connection (104: Connection reset by peer)
2016/03/16 15:38:52 [info] 1356#0: *108408 client 119.147.253.14 closed keepalive connection (104: Connection reset by peer)
2016/03/16 15:38:55 [info] 1356#0: *108416 client 116.211.104.64 closed keepalive connection (104: Connection reset by peer)
2016/03/16 15:38:55 [info] 1356#0: *108398 client 116.211.104.64 closed keepalive connection (104: Connection reset by peer)
2016/03/16 15:38:55 [info] 1356#0: *108419 client 116.211.104.64 closed keepalive connection (104: Connection reset by peer)
2016/03/16 15:38:55 [info] 1356#0: *108375 client 116.211.104.64 closed keepalive connection (104: Connection reset by peer)
```

看到  Nginx 日志里面有很多 `104: Connection reset by peer` 的错误

**Comment by fantasticfears** [comment]
我现在换到了阿里云深圳的机器：112.74.203.77

uname: Linux iZ946uhv97dZ 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

现在可以继续重现这个问题了；和网络有关？（UTC+8 早上没问题）

```
Gem::RemoteFetcher::FetchError: bad response Bad Gateway 502 (https://gems.ruby-china.org/gems/thin-1.6.3.gem)
/usr/local/lib/ruby/site_ruby/2.0.0/rubygems/remote_fetcher.rb:265:in `fetch_http'
/usr/local/lib/ruby/site_ruby/2.0.0/rubygems/remote_fetcher.rb:283:in `fetch_path'
/usr/local/lib/ruby/site_ruby/2.0.0/rubygems/remote_fetcher.rb:318:in `cache_update_path'
/usr/local/lib/ruby/site_ruby/2.0.0/rubygems/remote_fetcher.rb:182:in `download'
/usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/rubygems_integration.rb:599:in `download_gem'
/usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:409:in `fetch_gem'
/usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:115:in `install'
/usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/installer/gem_installer.rb:56:in `install'
/usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/installer/gem_installer.rb:14:in `install_from_spec'
/usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/installer/parallel_installer.rb:90:in `block in worker_pool'
/usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/worker.rb:55:in `call'
/usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/worker.rb:55:in `apply_func'
/usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/worker.rb:50:in `block in process_queue'
/usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/worker.rb:47:in `loop'
/usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/worker.rb:47:in `process_queue'
/usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/worker.rb:22:in `block (2 levels) in initialize'
```

我不太能懂为何会是 502，从我 bundle install 的时候出错，直觉上太像超时了；服务器那是 104，那说明是本地关了链接。那按照链路来说可以确定是 CDN 那的问题了吧。

不是的话就是再下一级？`us0.gems.ruby-china.org` 是做什么的..

**Comment by fantasticfears** [comment]
在 #9 更新后出现了新的证书错误。不是无法验证 CA 证书了，是不匹配了 ：

```
Gem::RemoteFetcher::FetchError: hostname "gems.ruby-china.org" does not match the server certificate (https://gems.ruby-china.org/gems/mini_portile-0.6.2.gem)
/usr/local/lib/ruby/site_ruby/2.0.0/rubygems/request.rb:89:in `rescue in connection_for'
/usr/local/lib/ruby/site_ruby/2.0.0/rubygems/request.rb:86:in `connection_for'
/usr/local/lib/ruby/site_ruby/2.0.0/rubygems/request.rb:141:in `perform_request'
/usr/local/lib/ruby/site_ruby/2.0.0/rubygems/request.rb:110:in `fetch'

```

**Comment by huacnlee** [comment]
请用浏览器打开 https://gems.ruby-china.org/

SSL 证书应该是正确的，是你本地的问题：

https://www.sslshopper.com/ssl-checker.html#hostname=https://gems.ruby-china.org/

<img width="601" alt="2016-03-17 15 03 26" src="https://cloud.githubusercontent.com/assets/5518/13838754/70e6cfcc-ec51-11e5-9b45-4d4385362ac8.png">

https://www.digicert.com/help/

<img width="458" alt="2016-03-17 15 04 15" src="https://cloud.githubusercontent.com/assets/5518/13838770/8e8030dc-ec51-11e5-8235-fbd240eb8ae3.png">

**Comment by fantasticfears** [comment]
我自己浏览器的证书肯定是没问题的...

以下是阿里云深圳的机器：112.74.203.77 出现的错误
uname: Linux iZ946uhv97dZ 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

我还是在用排除法来看 https 的问题。我再次[给 Ruby 指定证书](https://gist.github.com/fantasticfears/822793950e6c0ca38b4b)，不过还是会出现证书验证的问题，所以阿里云本地应该不至于出错。连国外的网还是会各种因为出口问题出错的，比如无法解析 github.com 的 DNS。

继续关注 TLS。nmap 检查过 cipher，也没啥问题，最后开始用 ssllabs 跑。

- 域名：https://www.ssllabs.com/ssltest/analyze.html?d=gems.ruby-china.org&latest
- `118.212.137.17`：https://www.ssllabs.com/ssltest/analyze.html?d=gems.ruby-china.org&s=118.212.137.17&latest

对 `118.212.137.17` 的报告就只有 SNI 需要支持（得分 A-，相当好）。容器里是 Ruby 2.0，Ubuntu 14.04 带的应该是 openssl 1.0.0f，是支持 SNI 的，判断 Ruby SNI 没问题。

然后 ssllabs 的多服务器报告里有连接和证书问题，指向其他几个相同域名的服务器：
![screen shot 2016-03-17 at 09 27 16](https://cloud.githubusercontent.com/assets/297343/13840372/788cad20-ec22-11e5-9c7c-a083c7cddb77.png)

- Unable to connect to the server:
  - `163.177.158.76` 
  - `163.177.158.77` 
  - `42.56.64.27` 
- Certificate not valid for domain name:
  - `153.3.167.17`
  - `123.129.203.157`
- Unexpected failure [RenegotiationTest]: Exception: Unexpected failure [RenegotiationTest]: Connection failed：
  - `153.3.167.16`

似乎 QCloud 还有些问题？

仍旧能重现的 bundle install 的错误（参考）：

1. 

```
Gem::RemoteFetcher::FetchError: bad response Bad Gateway 502 (https://gems.ruby-china.org/gems/pg-0.18.1.gem)
```
```
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Bad Gateway 502 (https://gems.ruby-china.org/specs.4.8.gz)
```

2.
```
I, [2016-03-17T07:47:36.421656 #36]  INFO -- : HTTP GET https://gems.ruby-china.org/api/v1/dependencies
Fetching source index from https://gems.ruby-china.org/
Need to query more than 500 gems. Downloading full index instead...
Could not find logster-1.0.0.3.pre in any of the sources
```

最后我没测试的就是 StartCOM 的证书在系统能够不够新了...root CA 06 年签的怎么应该也更新了...

以上，希望有所帮助。

**Comment by huacnlee** [comment]
```bash
$ openssl s_client -connect gems.ruby-china.org:443
```

检查本地 SSL 证书是否正确，请执行这个

**Comment by fantasticfears** [comment]
容器内证书是不对的。`Verify return code: 20 (unable to get local issuer certificate)`

部署过程中的 bundle install 已经流畅了
