### ISSUE TITLE
替换成淘宝镜像后还是报错,全部错误信息

### ISSUE THREAD

**Issue by ghs619** [ruby-china/rubygems-mirror#80]
hongwei@pool-100-2-20-113 bin $ gem install logstash-core -v '5.5.1'
ERROR:  Could not find a valid gem 'logstash-core' (= 5.5.1) in any repository
ERROR:  Possible alternatives: logstash-cli, logstasher, logstash-file, logstash-lite, logstash-logger

hongwei@pool-100-2-20-113 bin $ gem sources -l
*** CURRENT SOURCES ***

https://gems.ruby-china.org/

**Comment by kurapi** [comment]
。。。不是早就换成 ruby china 来维护了么，gem sources --add https://gems.ruby-china.org/。

**Comment by huacnlee** [comment]
版本更新可能不及时，手工同步一下

https://gems.ruby-china.org/add_spec
