### ISSUE TITLE
转换的源地址的时候 报错 404

### ISSUE THREAD

**Issue by wanshenghao** [ruby-china/rubygems-mirror#81]
使用http时报错为

C:\Users\A127>gem sources --add http://gems.ruby-china.org/ --remove http://ruby
gems.org/
ERROR:  SSL verification error at depth 1: unable to get local issuer certificat
e (20)
ERROR:  You must add /O=Digital Signature Trust Co./CN=DST Root CA X3 to your lo
cal trusted store
Error fetching http://gems.ruby-china.org/:
        SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: ce
rtificate verify failed (https://upyun.gems.ruby-china.org/specs.4.8.gz)

使用https报错为
C:\Users\A127>gem sources --add https://gems.ruby-china.org/ --remove http://rub
ygems.org/
ERROR:  SSL verification error at depth 1: unable to get local issuer certificat
e (20)
ERROR:  You must add /O=Digital Signature Trust Co./CN=DST Root CA X3 to your lo
cal trusted store
Error fetching https://gems.ruby-china.org/:
        SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: ce
rtificate verify failed (https://gems.ruby-china.org/specs.4.8.gz)

**Comment by jasl** [comment]
Ruby 版本是多少，这个问题很像 OpenSSL 的版本过低造成

**Comment by huacnlee** [comment]
重复问题 #78
