### ISSUE TITLE
gem update --system

### ISSUE THREAD

**Issue by zhangjianjun056** [ruby-china/rubygems-mirror#82]
你好，请问一下，我进行gem update --system 命令更新时，无论翻墙还是不翻墙都是报“Updating rubygems-update
ERROR:  While executing gem ... (OpenSSL::SSL::SSLError)
    hostname "upyun.gems.ruby-china.org" does not match the server certificate”错误，大神，请问有好的解决办法吗？

**Comment by huacnlee** [comment]
重复问题 #78
