### ISSUE TITLE
https证书显示不安全，docker下报SSL错误。

### ISSUE THREAD

**Issue by braid16** [ruby-china/rubygems-mirror#852]
执行docker build -f Dockerfile命令时报错。如下图https://
![屏幕截图 2022-10-11 090755](https://user-images.githubusercontent.com/43572305/194975295-96676d28-6139-4332-936b-d1ae552f76b9.png)
访问网站也显示不安全。
![屏幕截图 2022-10-11 090935](https://user-images.githubusercontent.com/43572305/194975392-a202fd91-9ab7-4a39-967d-7f242cc7ee4e.png)

**Comment by yu0winter** [comment]
The SSL Certificate is overdate for 'https://gems.ruby-china.com'. Right now open the website, the chome will alert the tip.
