### ISSUE TITLE
gems挂了

### ISSUE THREAD

**Issue by bysxiang** [ruby-china/rubygems-mirror#86]
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure (https://gems-ruby-china.b0.aicdn.com/specs.4.8.gz)

specs.4.8.gz网络错误

**Comment by huacnlee** [comment]
你连错了吧

怎么用的？

https://gems.ruby-china.org/

**Comment by bysxiang** [comment]
我就是用的这个地址啊，我就是执行了bundle install 一个gem，上午还没事儿，现在就不行了，我
wget "https://gems-ruby-china.b0.aicdn.com/specs.4.8.gz" 提示

OpenSSL: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
无法建立 SSL 连接。

**Comment by huacnlee** [comment]
不会到 https://gems-ruby-china.b0.aicdn.com 的，你的 DNS 有问题。

ping gems.ruby-china.org 看看，是指向什么地址

**Comment by bysxiang** [comment]
在我电信本地，指向 nm.ctn.aicdn.com (150.138.216.175)

**Comment by huacnlee** [comment]
> 我就是用的这个地址啊，我就是执行了bundle install 一个gem

具体点，Gemfile 贴出来看看
