### ISSUE TITLE
SSL错误

### ISSUE THREAD

**Issue by ymonke** [ruby-china/rubygems-mirror#89]
mac os
当我尝试执行 gem source -a https://gems.ruby-china.org
提示 Error fetching https://gems.ruby-china.org:
	SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure (https://gems-ruby-china.b0.aicdn.com/specs.4.8.gz)

**Comment by huacnlee** [comment]
你的 DNS 有问题，目前的部署是，请求 gems.ruby-china.org 不会到 gems-ruby-china.b0.aicdn.com 的

**Comment by huacnlee** [comment]
https://github.com/ruby-china/rubygems-mirror/issues/86
