### ISSUE TITLE
无法添加gems源

### ISSUE THREAD

**Issue by bysxiang** [ruby-china/rubygems-mirror#90]
gem sources --add https://gems.ruby-china.org显示：

Error fetching https://gems.ruby-china.org:
	SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure (https://gems-ruby-china.b0.aicdn.com/specs.4.8.gz)

通过wget "https://gems-ruby-china.b0.aicdn.com/specs.4.8.gz"也不行

**Comment by ourai** [comment]
本人 macOS High Sierra 下同样有此问题。Ruby 是通过 `rbenv` 装的，`rbenv` 是通过 Homebrew 装的。

相关版本信息如下：

```sh
mhc-oulei:~ oulei$ type ruby
ruby is hashed (/Users/oulei/.rbenv/shims/ruby)
mhc-oulei:~ oulei$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin17]
mhc-oulei:~ oulei$ type gem
gem is hashed (/Users/oulei/.rbenv/shims/gem)
mhc-oulei:~ oulei$ gem -v
2.4.5
```

**Comment by lansy00001** [comment]
请问，这个问题解决了吗？我现在添加国内源也有问题

**Comment by bysxiang** [comment]
@lansy00001 解决是解决了，有时部署还是会发生ssl证书错误，应该是ruby-china服务器有问题
