### ISSUE TITLE
mac   更新gem发现问题

### ISSUE THREAD

**Issue by BTig** [ruby-china/rubygems-mirror#92]
> Operation not permitted - /usr/bin/update_rubygems

代码：
`liuyongbService:~ liuyonghu$ sudo gem update --system`
`Password:`
`Updating rubygems-update`
`ERROR:  While executing gem ... (Errno::EPERM)`
`    Operation not permitted - /usr/bin/update_rubygems`
`liuyongbService:~ liuyonghu$ gem --version`
`2.6.7`

**Comment by BabyWong** [comment]
请问你解决了吗, 还有一个问题:
hwm:~ hwm$ gem --version
YAML safe loading is not available. Please upgrade psych to a version that supports safe loading (>= 2.0).
2.6.14
hwm:~ hwm$

**Comment by huacnlee** [comment]
以上两个问题与这个项目无关，有疑问，请上 Ruby China 发帖求助

**Comment by BTig** [comment]
哦 好的  谢谢
